steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/sample-311412/app1-repo:latest', '.' ]
    dir: code/

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/sample-311412/app1-repo:latest'
    ]

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'apply',
      '-f',
      'deployment-1.yaml'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
      - 'CLOUDSDK_CORE_PROJECT=sample-311412'
    
images:
  - 'gcr.io/sample-311412/app1-repo:latest'