apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-deployment"
  namespace: "default"
  labels:
    app: "my-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "my-deployment"
  template:
    metadata:
      labels:
        app: "my-deployment"
    spec:
      containers:
      - name: "app2"
        image: "gcr.io/sample-311412/app2-repo:latest"
        volumeMounts:
        - name: shared-data
          mountPath: /Shravanthi_PV_dir
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: pvc-new

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: default
spec:
  selector:
    app: my-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
